version: '3.4'

services:
  web:
    image: web
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3333:3333
    depends_on:
      - db

  db:
    image: bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: scarc
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "docker" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  certbot-nginx:
    image: certbot/certbot
    volumes:
      - ./certbot_data:/etc/letsencrypt
    command: certbot --nginx --agree-tos --no-eff-email --staging -d ec2-3-141-170-64.us-east-2.compute.amazonaws.com
    depends_on:
      - nginx
