version: '3.4'

services:
  web:
    image: web
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://docker:docker@db:5432/scarc
    ports:
      - 3333:3333
    depends_on:
      - db

  db:
    image: bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: scarc
    ports:
      - 5432:5432
