export * from './interfaces/air-conditioner.repository'
export * from './implementations/prisma-air-conditioner.repository'
export * from './interfaces/appointment.repository'
export * from './implementations/prisma-appointment.repository'
export * from './interfaces/room.repository'
export * from './implementations/prisma-room.repository'
